In [1]:
import re
import os 
import pandas as pd
import numpy as np

In [2]:
path = 'C:\\jupyter-notebook-files\\py3\\供电量数据'
files = os.listdir(path)

In [3]:
print (files)

['dataPreprocessing_drop_duplicates.csv', 'weather.csv', '月报表_月电量导出报表分析1401.xls', '月报表_月电量导出报表分析1402.xls', '月报表_月电量导出报表分析1403.xls', '月报表_月电量导出报表分析1404.xls', '月报表_月电量导出报表分析1405.xls', '月报表_月电量导出报表分析1406.xls', '月报表_月电量导出报表分析1407.xls', '月报表_月电量导出报表分析1408.xls', '月报表_月电量导出报表分析1409.xls', '月报表_月电量导出报表分析1410.xls', '月报表_月电量导出报表分析1411.xls', '月报表_月电量导出报表分析1412.xls', '月报表_月电量导出报表分析1501.xls', '月报表_月电量导出报表分析1502.xls', '月报表_月电量导出报表分析1503.xls', '月报表_月电量导出报表分析1504.xls', '月报表_月电量导出报表分析1505.xls', '月报表_月电量导出报表分析1506.xls', '月报表_月电量导出报表分析1507.xls', '月报表_月电量导出报表分析1508.xls', '月报表_月电量导出报表分析1509.xls', '月报表_月电量导出报表分析1510.xls', '月报表_月电量导出报表分析1511.xls', '月报表_月电量导出报表分析1512.xls', '月报表_月电量导出报表分析1601.xls', '月报表_月电量导出报表分析1602.xls', '月报表_月电量导出报表分析1603.xls', '月报表_月电量导出报表分析1604.xls', '月报表_月电量导出报表分析1605.xls', '月报表_月电量导出报表分析1606.xls', '月报表_月电量导出报表分析1607.xls', '月报表_月电量导出报表分析1608.xls', '月报表_月电量导出报表分析1609.xls', '月报表_月电量导出报表分析1610.xls', '月报表_月电量导出报表分析1611.xls', '月报表_月电量导出报表分析1612.xls', '月报表_月电量导出报表分析1701.xls', '月报表_月电量导出报表分析1702

In [4]:
os.chdir(path)

In [5]:
os.getcwd()

'C:\\jupyter-notebook-files\\py3\\供电量数据'

In [6]:
data_csv = pd.read_csv('dataPreprocessing_drop_duplicates.csv')

In [7]:
data_csv

Date  DailyElectricity
0     2014/01/01      92750.080000
1     2014/01/02     129481.000000
2     2014/01/03     161360.000000
3     2014/01/04     148608.000000
4     2014/01/05     138985.570786
5     2014/01/06     156729.000000
6     2014/01/07     165086.000000
7     2014/01/08     165642.000000
8     2014/01/09     164249.000000
9     2014/01/10     160739.000000
10    2014/01/11     160739.000000
11    2014/01/12     141705.000000
12    2014/01/13     151591.000000
13    2014/01/14     160998.000000
14    2014/01/15     159013.000000
15    2014/01/16     156966.000000
16    2014/01/17     154241.000000
17    2014/01/18     146531.000000
18    2014/01/19     129968.000000
19    2014/01/20     131560.000000
20    2014/01/21     131031.000000
21    2014/01/22     124284.000000
22    2014/01/23     115689.000000
23    2014/01/24     103834.000000
24    2014/01/25      89054.080000
25    2014/01/26      76452.400000
26    2014/01/27      67931.356070
27    2014/01/28      62932.000000
28    2014/01/29      54918.400000
29    2014/01/30      46260.480000
...          ...               ...
1370  2017/10/02     128278.000000
1371  2017/10/03     134228.000000
1372  2017/10/04     124562.000000
1373  2017/10/05     176747.000000
1374  2017/10/06     222162.000000
1375  2017/10/07     239224.000000
1376  2017/10/08     234974.000000
1377  2017/10/09     258824.000000
1378  2017/10/10     270325.000000
1379  2017/10/11     276078.000000
1380  2017/10/12     269369.000000
1381  2017/10/13     240332.000000
1382  2017/10/14     215387.000000
1383  2017/10/15     172456.000000
1384  2017/10/16     200448.000000
1385  2017/10/17     213012.000000
1386  2017/10/18     218822.000000
1387  2017/10/19     216934.000000
1388  2017/10/20     214429.000000
1389  2017/10/21     204973.000000
1390  2017/10/22     171328.000000
1391  2017/10/23     200922.000000
1392  2017/10/24     212075.000000
1393  2017/10/25     214232.000000
1394  2017/10/26     215863.000000
1395  2017/10/27     215716.000000
1396  2017/10/28     207028.000000
1397  2017/10/29     171648.000000
1398  2017/10/30     197594.000000
1399  2017/10/31     198831.000000

[1400 rows x 2 columns]

In [8]:
data_clip = data_csv['Date'].str.split('/',expand=True)

In [10]:
df_year = data_clip[0]

In [11]:
df_month = data_clip[1]

In [12]:
df_day = data_clip[2]

In [13]:
data_csv['year'] = df_year
data_csv['month'] = df_month
data_csv['day'] = df_day

In [19]:
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [76]:
# x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [32]:
# %matplotlib inline

In [77]:
# #随机森林
# #交叉验证
# from sklearn.ensemble import RandomForestRegressor
# max_features = [.1,.6,.7,.8,.9,1]
# test_loss = []
# test_accuarcy = []
# for max_feat in max_features:
#     clf = RandomForestRegressor(n_estimators=100,max_features=max_feat)
#     loss = -cross_val_score(clf,X,Y,cv=5,scoring='neg_mean_squared_error')#loss 损失函数
#     test_loss.append(loss.mean())

In [78]:
# plt.subplot(1,2,1)
# plt.plot(max_features,test_loss)
# plt.title("RF")

In [79]:
# clf_rf = RandomForestRegressor(n_estimators=100,max_features=.8)
# clf_rf.fit(x_train,y_train)

In [80]:
# result = clf_rf.predict(x_test)

In [81]:
# clf_rf.score(x_test,y_test)

In [82]:
# #1400 rows x 5 columns
# data_csv.describe

In [20]:
weather_csv = pd.read_csv('weather.csv',encoding = 'gb18030')

In [22]:
data_csv['weather'] = weather_csv['temperature'][:1400]

In [24]:
weather_clip = data_csv['weather'].str.split('/',expand=True)

In [25]:
weather_high = weather_clip[0].apply(lambda x:x.split('℃')[0])  
weather_low = weather_clip[1].apply(lambda x:x.split('℃')[0])

In [26]:
data_csv['Maximum temperature'] = weather_high
data_csv['Lowest temperature'] = weather_low

In [27]:
data_csv

Date  DailyElectricity  year month day    weather  \
0     2014/01/01      92750.080000  2014    01  01  20℃ / 12℃   
1     2014/01/02     129481.000000  2014    01  02  22℃ / 14℃   
2     2014/01/03     161360.000000  2014    01  03  22℃ / 14℃   
3     2014/01/04     148608.000000  2014    01  04  21℃ / 12℃   
4     2014/01/05     138985.570786  2014    01  05  20℃ / 13℃   
5     2014/01/06     156729.000000  2014    01  06  22℃ / 14℃   
6     2014/01/07     165086.000000  2014    01  07  22℃ / 15℃   
7     2014/01/08     165642.000000  2014    01  08  20℃ / 11℃   
8     2014/01/09     164249.000000  2014    01  09  18℃ / 11℃   
9     2014/01/10     160739.000000  2014    01  10  17℃ / 13℃   
10    2014/01/11     160739.000000  2014    01  11  20℃ / 13℃   
11    2014/01/12     141705.000000  2014    01  12   20℃ / 9℃   
12    2014/01/13     151591.000000  2014    01  13   16℃ / 8℃   
13    2014/01/14     160998.000000  2014    01  14   16℃ / 7℃   
14    2014/01/15     159013.000000  2014    01  15   17℃ / 8℃   
15    2014/01/16     156966.000000  2014    01  16  18℃ / 10℃   
16    2014/01/17     154241.000000  2014    01  17  20℃ / 10℃   
17    2014/01/18     146531.000000  2014    01  18   20℃ / 9℃   
18    2014/01/19     129968.000000  2014    01  19  20℃ / 10℃   
19    2014/01/20     131560.000000  2014    01  20   20℃ / 9℃   
20    2014/01/21     131031.000000  2014    01  21   19℃ / 8℃   
21    2014/01/22     124284.000000  2014    01  22   18℃ / 9℃   
22    2014/01/23     115689.000000  2014    01  23   18℃ / 9℃   
23    2014/01/24     103834.000000  2014    01  24  21℃ / 13℃   
24    2014/01/25      89054.080000  2014    01  25  22℃ / 15℃   
25    2014/01/26      76452.400000  2014    01  26  25℃ / 15℃   
26    2014/01/27      67931.356070  2014    01  27  22℃ / 15℃   
27    2014/01/28      62932.000000  2014    01  28  23℃ / 15℃   
28    2014/01/29      54918.400000  2014    01  29  24℃ / 16℃   
29    2014/01/30      46260.480000  2014    01  30  26℃ / 16℃   
...          ...               ...   ...   ...  ..        ...   
1370  2017/10/02     128278.000000  2017    10  02  32℃ / 27℃   
1371  2017/10/03     134228.000000  2017    10  03  34℃ / 27℃   
1372  2017/10/04     124562.000000  2017    10  04  31℃ / 25℃   
1373  2017/10/05     176747.000000  2017    10  05  32℃ / 25℃   
1374  2017/10/06     222162.000000  2017    10  06  33℃ / 26℃   
1375  2017/10/07     239224.000000  2017    10  07  33℃ / 26℃   
1376  2017/10/08     234974.000000  2017    10  08  34℃ / 27℃   
1377  2017/10/09     258824.000000  2017    10  09  33℃ / 26℃   
1378  2017/10/10     270325.000000  2017    10  10  33℃ / 26℃   
1379  2017/10/11     276078.000000  2017    10  11  33℃ / 26℃   
1380  2017/10/12     269369.000000  2017    10  12  32℃ / 26℃   
1381  2017/10/13     240332.000000  2017    10  13  30℃ / 22℃   
1382  2017/10/14     215387.000000  2017    10  14  27℃ / 22℃   
1383  2017/10/15     172456.000000  2017    10  15  23℃ / 20℃   
1384  2017/10/16     200448.000000  2017    10  16  24℃ / 20℃   
1385  2017/10/17     213012.000000  2017    10  17  28℃ / 21℃   
1386  2017/10/18     218822.000000  2017    10  18  29℃ / 22℃   
1387  2017/10/19     216934.000000  2017    10  19  28℃ / 22℃   
1388  2017/10/20     214429.000000  2017    10  20  29℃ / 21℃   
1389  2017/10/21     204973.000000  2017    10  21  28℃ / 20℃   
1390  2017/10/22     171328.000000  2017    10  22  26℃ / 17℃   
1391  2017/10/23     200922.000000  2017    10  23  26℃ / 17℃   
1392  2017/10/24     212075.000000  2017    10  24  28℃ / 20℃   
1393  2017/10/25     214232.000000  2017    10  25  28℃ / 20℃   
1394  2017/10/26     215863.000000  2017    10  26  28℃ / 20℃   
1395  2017/10/27     215716.000000  2017    10  27  28℃ / 20℃   
1396  2017/10/28     207028.000000  2017    10  28  29℃ / 19℃   
1397  2017/10/29     171648.000000  2017    10  29  27℃ / 19℃   
1398  2017/10/30     197594.000000  2017    10  30  26℃ / 16℃   
1399  2017/10/31     198831.000000  2017    10 

In [28]:
X_GPR = data_csv[['year','month','day','Maximum temperature','Lowest temperature']].values
Y_GPR = data_csv[['DailyElectricity']].values

In [36]:
# x_train_gpr,x_test_gpr,y_train_gpr,y_test_gpr = train_test_split(X_GPR,Y_GPR,test_size=0.3,random_state=0)
x_train_gpr = X_GPR[:1369]
y_train_gpr = Y_GPR[:1369]
x_test_gpr = X_GPR[1369:]
y_test_gpr = Y_GPR[1369:]

In [30]:
from sklearn.gaussian_process import GaussianProcessRegressor  
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C# REF就是高斯核函数  

In [47]:
#核函数
kernel = C(0.1, (0.001,0.1))*RBF(0.5,(1e-4,1000))

In [48]:
#创建高斯过程回归,并训练
# alpha就是添加到协方差矩阵对角线上的值，n_restarts_optimizer规定了优化过程的次数
reg = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10,alpha=0.1)

In [49]:
reg.fit(x_train_gpr,y_train_gpr)

GaussianProcessRegressor(alpha=0.1, copy_X_train=True,
             kernel=0.316**2 * RBF(length_scale=0.5),
             n_restarts_optimizer=10, normalize_y=False,
             optimizer='fmin_l_bfgs_b', random_state=None)

In [34]:
result_gpr = reg.predict(x_test_gpr)

In [50]:
reg.score(x_test_gpr,y_test_gpr)

0.16670391864222822

In [193]:
from mpl_toolkits.mplot3d import Axes3D#实现数据可视化3D  

In [51]:
from sklearn import preprocessing

In [52]:
X_GPR_n = data_csv[['year','month','day','Maximum temperature','Lowest temperature']].values
Y_GPR_n = data_csv[['DailyElectricity']].values

In [53]:
x_train_gpr_n = X_GPR_n[:1369]
y_train_gpr_n = Y_GPR_n[:1369]
x_test_gpr_n = X_GPR_n[1369:]
y_test_gpr_n = Y_GPR_n[1369:]

In [54]:
scaler=preprocessing.StandardScaler()

In [55]:
x_train_gpr_n_scaled = scaler.fit_transform(x_train_gpr_n)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [56]:
print(x_train_gpr_n_scaled.mean(axis=0))
print(x_train_gpr_n_scaled.std(axis=0))

[-5.58053725e-14 -7.78534773e-17  1.29755795e-17  4.15218545e-17
  1.03804636e-17]
[1. 1. 1. 1. 1.]


In [57]:
x_test_gpr_n_scaled = scaler.transform(x_test_gpr_n)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [58]:
print(x_test_gpr_n_scaled.mean(axis=0))
print(x_test_gpr_n_scaled.std(axis=0))

[1.47835573 1.12837176 0.03155553 0.38522452 0.28486979]
[4.44089210e-16 2.22044605e-16 1.01681106e+00 4.92025061e-01
 5.94324574e-01]


In [59]:
from sklearn.gaussian_process import GaussianProcessRegressor  
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C# REF就是高斯核函数  

In [72]:
#核函数
kernel = C(0.01, (0.001,0.1))*RBF(0.5,(1e-4,10))
# kernel = RBF(1.0,(1e-4,10))
#创建高斯过程回归,并训练
# alpha就是添加到协方差矩阵对角线上的值，n_restarts_optimizer规定了优化过程的次数
reg = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10,alpha=0.1)

In [73]:
reg.fit(x_train_gpr_n_scaled,y_train_gpr_n)

GaussianProcessRegressor(alpha=0.1, copy_X_train=True,
             kernel=0.1**2 * RBF(length_scale=0.5),
             n_restarts_optimizer=10, normalize_y=False,
             optimizer='fmin_l_bfgs_b', random_state=None)

In [253]:
result_gpr = reg.predict(x_test_gpr_n_scaled)

In [75]:
reg.score(x_test_gpr_n_scaled,y_test_gpr_n)

0.07158780091941086

In [67]:
clf_rf = RandomForestRegressor(n_estimators=100,max_features=.6)
clf_rf.fit(x_train_gpr_n_scaled,y_train_gpr_n)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=0.6, max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [68]:
y_train_gpr_n.ravel()

array([ 92750.08, 129481.  , 161360.  , ..., 281262.  , 270311.  ,
       236674.  ])

In [69]:
clf_rf.score(x_test_gpr_n_scaled,y_test_gpr_n)

-0.4370027408599726

In [70]:
from sklearn.ensemble import RandomForestRegressor
max_features = [.1,.6,.7,.8,.9,1]
test_loss = []
test_accuarcy = []
for max_feat in max_features:
    clf = RandomForestRegressor(n_estimators=100,max_features=max_feat)
    loss = -cross_val_score(clf,x_train_gpr_n_scaled,y_train_gpr_n,cv=5,scoring='neg_mean_squared_error')#loss 损失函数
    test_loss.append(loss.mean())

C:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please ch

In [83]:
# plt.subplot(1,2,1)
# plt.plot(max_features,test_loss)
# plt.title("RF")